### ISSUE TITLE
Possible to use on client-side web page?

### ISSUE THREAD

**Issue by benlwilliams** [tmcw/wcag-contrast#3]
I'm looking for a tool to work on a test page I've made of all my company's various branding colors.  Is it possible to run this script client-side so that I can just include all the needed code in my web page?  I'm looping through all our text-color/bg-color combinations and would like to use this to output the compliance pass/fail with each combination.

**Comment by tmcw** [comment]
Yep, you can run this client-side. Either include it in a project with browserify or webpack, or use browserify to generate a bundle.

**Comment by benlwilliams** [comment]
Ok. I'll give it a try. Thanks.
