### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by mattdesl** [tmcw/wcag-contrast#35]
Getting this error when trying to use this library via browserify/frontend.

`esm.js:1 Uncaught TypeError: Cannot read property 'startsWith' of undefined`

I'm in latest Chrome so it does support string `startsWith()`, my first guess is that the problem lies with `esm` which is an unusual and non-standard way of bundling up modules (I've run into the same problem with `esm` before in other modules).

**Comment by jdalton** [comment]
Hi @tmcw!

You can enable browserify bundles _(as well as webpack/rollup targeted for browsers)_ by adding the `browser` field much like the `module` that's already in your `package.json`:

```json
"browser": "index.mjs",
"module": "index.mjs",
```

**Update:**

webpack [defaults to](https://webpack.js.org/configuration/resolve/#resolve-mainfields) resolving `'browser'`, then `'module'`, then `'main'` when the `target` is unspecified, `webworker`, or `web` which means you'd need the `browser` field explicitly specified for Browserify or [rollup](https://github.com/rollup/rollup-plugin-node-resolve/tree/master#usage) with the `browser` option.

**Comment by tmcw** [comment]
Thanks for the suggestion! I'm not sure if that's a path forward: browserify as-is doesn't support ES6 export/import syntax, so if I currently do:

```diff
diff --git a/package.json b/package.json
index 668274d..33ba3bc 100644
--- a/package.json
+++ b/package.json
@@ -4,6 +4,7 @@
   "description": "evaluate the wcag color contrast score for two colors",
   "main": "index.js",
   "module": "index.mjs",
+  "browser": "index.mjs",
   "directories": {
     "test": "test"
   },
```

And

`foo.js`

```js
require('./');
```

And

```
s/wcag-contrast [master●] » npx browserify foo.js
npx: installed 136 in 7.505s

/Users/tmcw/s/wcag-contrast/index.mjs:1
import relativeLuminance from "relative-luminance";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Afacit, browserify really requires a baked CJS or UMD bundle in order to work with a module with a setup like this one.

**Comment by jdalton** [comment]
@tmcw 

While not 💯 I think it's part of  the path forward. @mattdesl is up for doing an investigation into creating a browserify transform for streamlining its `import/export` syntax support. 

The transform can address the broader issue of ES module syntax support within Browserify. On your end the `browser` field will signal to other ES-enabled bundlers like (webpack, rollup, parcel, microbundle, etc/) that the `index.mjs` is the intended entry point for them for their browser targeted bundles.

**Comment by jdalton** [comment]
The transform can address the broader issue of ES module syntax support within Browserify. On your end the `browser` field will signal to other ES-enabled bundlers like (webpack, rollup, parcel, microbundle) that the `index.mjs` is the intended entry point for them for their browser targeted bundles.

**Comment by tmcw** [comment]
Yep, though I'll probably hold on making any changes until there's a browserify-related solution: currently, adding a browser field trades one error for another.

**Comment by mattdesl** [comment]
I'm experimenting with writing a browserify plugin, something like `browserify index.js -p esmify` which will handle:

- `"module"` resolution in package.json (should this take precedence over browser field or not?)
- add a default `.mjs` extension to browserify (is that needed?)
- use babel + CommonJS plugin to transform globally any scripts with `import` / `export` syntax into CommonJS

**Comment by jdalton** [comment]
@mattdesl 

> "module" resolution in package.json (should this take precedence over browser field or not?)

You can model after the webpack [`mainFields` option](https://webpack.js.org/configuration/resolve/#resolve-mainfields) which defaults to checking `['browser', 'module', 'main']` (in ascending order).

> add a default `.mjs` extension to browserify (is that needed?)

The `.mjs` extension is not required for browser code so `.js` will do. 
As a plus, the `.js` extension works without having to configure your server for a new extension. 

On the Node-`--experimental-modules`-side the use of an extension to disambiguate is likely to become a reality. However, it may not end up being the-only-way-to-disambiguate. The ecosystem as treated `.mjs` as more locked down since the rules around it haven't been ironed out _(they want to avoid prematurely extending features or allowances that may not make it into its final form)_. 

> use babel + CommonJS plugin to transform globally any scripts with import / export syntax into CommonJS

The use of Babel 7 [`overrides` option](https://babeljs.io/docs/en/next/babelrc.html#overrides) will help here.

**Comment by mattdesl** [comment]
> The .mjs extension is not required for browser code so .js will do.

However, if I am trying to build an inter-op tool to support generic ESM-authored code, it seems necessary to support requires like `./foo` which should resolve to `./foo.mjs` (and – as I understand from current murky discussions, take precedence over `./foo.js`).

I haven't found any clear and final spec on this yet that actually spans Node.js and the browser, perhaps you could guide me to something? Otherwise I'm not even sure how to write & test a module/tool for this, aside from just making sweeping assumptions and copy + pasting what some other libraries are trending toward. (It is quickly becoming apparent why browserify maintainers are holding off adding ESM to their core...)

I've found some discussion [here](https://medium.com/@giltayar/native-es-modules-in-nodejs-status-and-future-directions-part-i-ee5ea3001f71) but it seems like loose guidelines that may or may not be accepted.

**Comment by jdalton** [comment]
@mattdesl

Ah I misunderstood.
I thought you were asking to add an extension to the generated bundle filename.

> add a default .mjs extension to browserify (is that needed?)

Yes, browserify should resolve `.mjs` files. Yes, `.mjs` should [resolve before](https://github.com/nodejs/node/blob/65f617314d1ea2df8b9e16fb7e7078b5913c749c/src/module_wrap.cc#L45) `.js`.

**Update:**

Besides loading modules with ESM syntax, the `esm` loader can also be used to resolve `.mjs` and other files so you don't have to copy/paste lots of code.

```js
const loader = require("esm")(module)
console.log(loader.resolve("./foo") // will resolve to the path of foo.mjs if it exists.
```

The `esm` loader supports the [`loader.resolve`](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_require_resolve_request_options) and [`loader.resolve.paths`](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_require_resolve_paths_request) methods in all supported Node versions (Node 6+).

**Comment by jdalton** [comment]
Besides loading files with ESM support the `esm` loader can also be used to resolve `.mjs` and other files so you don't have to copy/paste lots of code.

```js
const loader = require("esm")(module)
console.log(loader.resolve("./foo") // will resolve to the path of foo.mjs if it exists.
```

The `esm` loader supports [`loader.resolve`](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_require_resolve_request_options) and [`loader.resolve.paths`](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_require_resolve_paths_request) in all supported Node versions (Node 6+).

**Comment by mattdesl** [comment]
I ended up writing an ESM plugin for browserify:
https://github.com/mattdesl/esmify

IMHO not a great solution to the problem (of people publishing not-yet-standard syntax on npm), but better than not being able to import modules like this.

I'm sure my tool will not last long, as the spec seems to be in constant flux and once browsers + Node.js converges the import/export syntax and tooling might end up looking fairly different.

**Comment by jdalton** [comment]
@mattdesl Awesome!

**Comment by tmcw** [comment]
All right, per this module - I've reworked this and am reworking the rest of my lil modules to provide umd, cjs, and es6 module entry points, pre-baked. It's better for notebooks, generally should be more consumer-friendly, and I'm using microbundle for the purpose, which is working pretty well. That should resolve this issue, because the `main` entry point will be CJS.

**Comment by hirenpanchal1401** [comment]
Try this in REPL...

var Y;
Y.startsWith("abc")

you will get error : Cannot read property 'startsWith' of undefined
because Y is undefined. So you have to assign any value or empty string to Y.
After assigning any value to Y result will be true or false.

**Comment by chathurangaayesh** [comment]
Pleas help to fix this error.
i was try to install ionic 

npm ERR! Cannot read property 'startsWith' of null

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bayesh\AppData\Roaming\npm-cache\_logs\2019-07-25T05_01_09
_330Z-debug.log
![Screenshot_1](https://user-images.githubusercontent.com/42993713/61847197-6e136300-aec7-11e9-89b7-755bc9ab898c.png)
